# Generated by Django 4.1.1 on 2022-10-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_guide',
            name='tg_date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tour_guide',
            name='tg_rating',
            field=models.FloatField(null=True),
        ),
    ]
