# Generated by Django 4.1.1 on 2022-10-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='t_date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
