# Generated by Django 4.1.1 on 2022-10-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
