# Generated by Django 4.1.1 on 2022-10-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.FloatField(null=True),
        ),
    ]
