# Generated by Django 4.1.1 on 2022-10-23 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourist_spot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergency',
            fields=[
                ('em_id', models.IntegerField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=50)),
                ('ts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourist_spot.tourist_spot')),
            ],
        ),
    ]
