# Generated by Django 4.1.1 on 2022-10-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.IntegerField(primary_key=2, serialize=False)),
                ('s_name', models.CharField(max_length=50)),
                ('s_sec', models.CharField(max_length=2)),
                ('s_dep', models.CharField(max_length=4)),
                ('about', models.TextField()),
            ],
        ),
    ]
