# Generated by Django 4.1.1 on 2022-10-17 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
