# Generated by Django 4.1.1 on 2022-10-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('U_id', models.IntegerField(primary_key=True, serialize=False)),
                ('U_first_name', models.CharField(max_length=50)),
                ('U_last_name', models.CharField(max_length=50)),
                ('U_email', models.CharField(max_length=50)),
                ('U_name', models.CharField(max_length=50)),
                ('U_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
