# Generated by Django 4.1.1 on 2022-10-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_spot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist_spot',
            name='spot_details',
            field=models.TextField(null=True),
        ),
    ]
